# Push back changes to main actions-subtree repository
on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/*'

name: Push back to actions-subtree

jobs:
  create_key:
    runs-on: ubuntu-18.04

    name: Push on change

    steps:
      - name: Check out our repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git log HEAD^.. --pretty=format:"git config --global user.name '%an' && git config --global user.email '%ae'" | tee /dev/stderr | sh

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACTIONS_SUBTREE_KEY_DEPLOY }}
          known_hosts: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
          name: id_rsa # optional

      - name: Pull subtree
        run: |
          set -x
          git subtree pull -m "Merge from actions-subtree" --prefix=.github/workflows git@github.com:${{ secrets.ACTIONS_SUBTREE_REMOTE_REPO }} ${{ github.repository }} || (git rm -rf .github/workflows/.github && git add .github/workflows)
          git rm -rf --ignore-unmatch .github/workflows/.github
          git commit --amend --no-edit || true

      - name: Push subtree
        run: |
          set -x
          git subtree push --prefix=.github/workflows git@github.com:${{ secrets.ACTIONS_SUBTREE_REMOTE_REPO }} ${{ github.repository }}
