on:
  push:
    branches:
      - '*/*'

name: Push on change

jobs:
  create_key:
    runs-on: ubuntu-18.04

    name: Push on change

    steps:
      - name: Check out our repository
        uses: actions/checkout@v2

      - name: Get branch name
        id: remote_repo
        run: |
          echo "::set-output name=slug::$(echo $GITHUB_REF | sed 's#refs/heads/##')"
        shell: bash

      - name: Check out remote repository
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.remote_repo.outputs.slug }}
          path: remote/${{ steps.remote_repo.outputs.slug }}

      - name: Clean .github from entire history
        run: |
          FILTER_BRANCH_SQUELCH_WARNING=1 git filter-branch --index-filter 'git rm -rf --cached --ignore-unmatch .github' --prune-empty

      - name: Merge subtree
        run: |
          set -x
          cd remote/${{ steps.remote_repo.outputs.slug }}
          git subtree pull -m "Merge from actions-subtree" --prefix=.github/workflows ../../.. ${{ steps.remote_repo.outputs.slug }}
          git push
